FROM node:22

WORKDIR /app

COPY 1.cortexAI/backend/services/auth/package*.json ./

RUN npm install

COPY 1.cortexAI/backend/services/auth/ ./

COPY 1.cortexAI/backend/shared/ /shared/

RUN mkdir -p /shared/node_modules && cp -r /app/node_modules/ioredis /shared/node_modules/

EXPOSE 8001

CMD ["npm", "start"]
