FROM node:22

WORKDIR /app

COPY 1.cortexAI/backend/services/auth/package*.json ./

RUN npm install

COPY 1.cortexAI/backend/services/auth/ ./
COPY 1.cortexAI/backend/shared/ /shared/

RUN rm -rf /shared/node_modules && ln -s /app/node_modules /shared/node_modules

EXPOSE 8001

CMD ["npm", "start"]
